### ISSUE TITLE
Not able to use Examples from repo example

### ISSUE THREAD

**Issue by manish2612** [brandonmcconnell/scss-typewriter#1]
I copied typed.scss in local folder and imported it `@import '../mixins/typed.scss';` in local base.scss
if we use mixin like below

`@include typed("String 1", "String 2");`

its throwing error:
`SassError: Invalid CSS after "... 0.08, 1, 8.88,": expected selector, was '"String 1" "String '
        on line 405 of styles/mixins/typed.scss, in mixin 'typed'
        from line 71 of styles/base/base.scss
        from line 3 of styles/index.scss`

**Comment by CvdL-UM** [comment]
From [https://sass-lang.com/documentation/at-rules/import](https://sass-lang.com/documentation/at-rules/import):
```
💡 Fun fact:
Unlike some other languages, Sass doesn’t require that you use ./ for relative imports. Relative imports are always available.
```
So you can actually use `@import 'mixins/typed';`

And make sure you are using a selector, for example:
```
h1 {
    @include typed("String 1", "String 2");
}
```

**Comment by brandonmcconnell** [comment]
Thanks @CvdL-UM!

@Manish2612 did that solve the issue you were experiencing?

**Comment by manish2612** [comment]
> Thanks @CvdL-UM!
> 
> @Manish2612 did that solve the issue you were experiencing?

Yes. Thanks @CvdL-UM
