### ISSUE TITLE
[Deprecation Warning] Future change to interpolation operator in SASS

### ISSUE THREAD

**Issue by richardsonian** [brandonmcconnell/scss-typewriter#11]
I'm compiling typed.scss using the [jekyll-sass-converter v1.5.2](https://github.com/jekyll/jekyll-sass-converter/releases/tag/v1.5.2) gem under [Jekyll 3.8.5](https://github.com/jekyll/jekyll/releases/tag/v3.8.5) (Ruby 2.7.7).

This mean's I'm compiling typed.scss using [Ruby SASS 3.4](https://rubygems.org/gems/sass/versions/3.4.25). Ruby sass has been [entirely deprecated](https://sass-lang.com/ruby-sass) since 2019, but I'd like to flag this issue anyways in case the syntax change causes any issues for DartSass or LibSass users.

I'm getting this warning that the following use of `#{}` syntax will be deprecated in a "future version"

```
DEPRECATION WARNING on line 416 of {path_to_library}/typed.scss:
#{} interpolation near operators will be simplified in a future version of Sass.
To preserve the current behavior, use quotes:

  unquote("#{str-slice($fwd-string, 1, $j)}")

DEPRECATION WARNING on line 418 of {path_to_library}/typed.scss:
#{} interpolation near operators will be simplified in a future version of Sass.
To preserve the current behavior, use quotes:

  unquote("#{str-slice($bwd-string, 1, $bwd-length - ($j - $fwd-length))}")
```

**Comment by brandonmcconnell** [comment]
@richardsonian Thanks for the report. I'll try to get a fix for this into a PR today. Would you be available to test once that's ready?

**Comment by richardsonian** [comment]
Yes, happy to test in my Jekyll dev environment. I think it’s probably most important to test for dartsass, though, which I’m not set up to do.

**Comment by brandonmcconnell** [comment]
@richardsonian Could you please test and respond to my related PR #12, which should resolve this issue? Thanks!
