### ISSUE TITLE
Feature request: adjustable animation delay

### ISSUE THREAD

**Issue by risbi0** [brandonmcconnell/scss-typewriter#14]
Whenever the page I'm using the animation on is reloaded, other animations in the page started earlier than the type animation, which was like around a second before it starts. It would be nice if it starts as soon as possible.

**Comment by brandonmcconnell** [comment]
@risbi0 Please check the `delay` property within the `$options` map that can be passed via the final argument. The default is `1` (1sec) but this can be changed to any other seconds value. It appears passing that value as `0` would be exactly what you're looking for.

For example:

```scss
@include typed("String 1", "String 2", null, (delay: 0));
```

I'll go ahead and close this issue now, but please re-open this issue and/or comment back if this does not resolve your question. Thanks for using Typed.css and opening this issue! 🥳
