### ISSUE TITLE
Character-timed delay syntax is displayed if included in end-on string

### ISSUE THREAD

**Issue by greyskin** [brandonmcconnell/scss-typewriter#15]
Including a character-timed delay in an `end-on` string results in the code being displayed.

**Example:**
```
.test {
    @include typed(
        "Testing...",
        1,
        (
            iterations: 1,
            end-on: "one, two and... <[15]>three")
    );
}
```

Results in the `end-on` string being temporarily displayed as:
> one, two and... <[15]

before the "<[15]" disappears and the correct string is displayed:
> one, two and... three

**Comment by greyskin** [comment]
On further testing, it appears the character-timed delay syntax is also displayed in standard strings if the `iterations` property is set to 0.

Not sure if that additional info is useful in identifying the cause of this.

I'm using Chrome Version 110.0.5481.180 (Official Build) (64-bit)

**Comment by brandonmcconnell** [comment]
@greyskin Hey Luke, thanks for the report. I'm pretty swamped with work-work at the moment, but I'll try to get a fix for this in the next week or two. Really appreciate it!

**Comment by brandonmcconnell** [comment]
@greyskin It turned out to be a much simpler fix than I expected.

Resolved via commit [53c86a](https://github.com/brandonmcconnell/typed.css/commit/53c86a8b3495d30b1f45a962ba02beb7bbb02397)

**Comment by brandonmcconnell** [comment]
@greyskin Please test and let me know if this update fixes the issue for you!

**Comment by greyskin** [comment]
@brandonmcconnell yes this fixed it! 👍  Thanks so much!
