### ISSUE TITLE
Detect end of animation with javascript

### ISSUE THREAD

**Issue by alexandredesane** [brandonmcconnell/scss-typewriter#21]
Hello,
sorry for opening an issue, this is not an issue. What a Great work you did with that mixin, thank you so much. 

I was wondering if there is a day to detect the end of the animation using js, if so could you help me ?

**Comment by alexandredesane** [comment]
Just figured it out with 
`const animated = document.querySelector(".animated");

animated.addEventListener("animationend", () => {
  console.log("Animation ended");
});`

**Comment by brandonmcconnell** [comment]
@alexandredesane Amazing! Thanks 🙌🏼
